import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart,
  BrushCleaning,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Copy,
  Download,
  Droplets,
  Eye,
  FileText,
  Flag,
  GripVertical,
  History,
  House,
  Inbox,
  LayoutDashboard,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreHorizontal,
  Pencil,
  Pin,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Search,
  Send,
  Settings2,
  ShieldCheck,
  SpellCheck,
  StickyNote,
  Trash2,
  TriangleAlert,
  TrendingDown,
  TrendingUp,
  Truck,
  UserRoundPlus,
  Users,
  Waves,
  Wifi,
  X
} from "lucide-react";

  const icons = {
  dashboard: LayoutDashboard,
  home: House,
  records: ClipboardList,
  users: Users,
  telegram: Send,
  logs: FileText,
  refresh: RefreshCw,
  logout: LogOut,
  search: Search,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  map: MapPin,
  transport: Truck,
  water: Droplets,
  sewer: Waves,
  broom: BrushCleaning,
  waste: Trash2,
  copy: Copy,
  eye: Eye,
  edit: Pencil,
  plus: Plus,
  archive: Archive,
  history: History,
  activity: Activity,
  warning: TriangleAlert,
  success: CheckCircle2,
  userCreated: UserRoundPlus,
  auth: ShieldCheck,
  settings: Settings2,
  notes: StickyNote,
  more: MoreHorizontal,
  menu: Menu,
  download: Download,
  print: Printer,
  filter: Settings2,
  chevronDown: ChevronDown,
  calendar: CalendarDays,
  mail: Mail,
  trash: Trash2,
  wifi: Wifi,
  chevronRight: ChevronRight,
  clipboard: ClipboardCheck,
  play: Play,
  flag: Flag,
  checkCircle: CheckCircle2,
  inbox: Inbox,
  barChart: BarChart,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  close: X,
  pin: Pin,
  grip: GripVertical,
  send: Send,
  spellCheck: SpellCheck
};

export const Icon = ({ name, className = "" }) => {
  const LucideIcon = icons[name] || FileText;

  return (
    <span className={`app-icon ${className}`.trim()} aria-hidden="true">
      <LucideIcon width="100%" height="100%" strokeWidth={1.8} />
    </span>
  );
};

export const actionIconName = (action) =>
  (
    {
      "auth.login": "auth",
      "auth.logout": "logout",
      "auth.password_changed": "success",
      "user.created": "userCreated",
      "user.role_updated": "users",
      "padron.updated": "refresh",
      "report.generated": "print",
      "map_point.created": "map",
      "map_point.validated": "success",
      "map_point.deleted": "archive",
      "transport.route_created": "transport",
      "transport.route_updated": "transport",
      "transport.route_started": "transport",
      "transport.route_completed": "success",
      "transport.position_logged": "map",
      "transport.route_alert": "warning",
      "inmueble.created": "plus",
      "inmueble.updated": "records",
      "inmueble.printed": "records",
      "inmueble.archived": "archive",
      "inmueble.deleted": "logout",
      "inmueble.restored": "refresh",
      "inmueble.photo_attached": "activity"
    }[action] ?? "activity"
  );
