import { useMemo, useState } from "react";
import { Icon } from "../../components/Icon";
import { formatCurrency } from "../../utils/formatting";
import { formatSpanishDate } from "../../utils/datesAndBusiness";
import { debtRanking, sumSelectedDebt } from "./dashboardSelectors";
import "./dashboard.css";

export default function DashboardWorkspace({ model }) {
  const [debtMetric, setDebtMetric] = useState("total");
  const [selectedBarrios, setSelectedBarrios] = useState([]);
  const [moreOpen, setMoreOpen] = useState(false);
  const ranking = useMemo(() => debtRanking(model.debtBarrios, debtMetric), [model.debtBarrios, debtMetric]);
  const selectedDebt = useMemo(() => sumSelectedDebt(ranking, selectedBarrios), [ranking, selectedBarrios]);
  const maxDebt = Math.max(1, ...ranking.map((item) => item.value));
  const toggleBarrio = (name) => setSelectedBarrios((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]);
  return <main className="dashboard-workspace">
    <header className="dashboard-new-header dashboard-glass"><div><span>Resumen operativo · {formatSpanishDate(new Date())}</span><h1>Buenos días, {model.userName}</h1><p>Información crítica, actividad y accesos del sistema en una sola vista.</p></div><div className="dashboard-live"><i /><strong>Sistema en vivo</strong><small>{model.syncLabel}</small></div><div className="dashboard-new-actions"><button type="button" onClick={() => model.navigate("records")}><Icon name="plus" />Nueva ficha</button><button type="button" className="button-secondary" onClick={() => model.navigate("lookup")}><Icon name="search" />Buscar clave</button><div><button type="button" className="button-secondary" aria-expanded={moreOpen} onClick={() => setMoreOpen((v) => !v)}>Más acciones ▾</button>{moreOpen ? <nav><button onClick={() => model.navigate("map")}>Ir a campo</button><button onClick={() => model.navigate("logs")}>Revisar actividad</button><button onClick={() => model.navigate("executiveReport")}>Operaciones realizadas</button></nav> : null}</div></div></header>
    <section className={`dashboard-online-rail ${model.onlineUsers.length ? "has-users" : "is-empty"}`} aria-label="Usuarios en línea"><div className="dashboard-online-rail-head"><span className="dashboard-online-rail-kicker"><span className="dashboard-online-rail-dot" />Equipo en vivo</span><strong>{model.onlineUsers.length} usuarios en línea</strong></div>{model.onlineUsers.length ? <div className="dashboard-online-rail-window"><div className="dashboard-online-rail-track" style={{ "--rail-duration": `${Math.max(18, model.onlineUsers.length * 7)}s` }}>{[...model.onlineUsers, ...model.onlineUsers].map((user, index) => <article key={`${user.id}-${index}`} className="dashboard-online-rail-card"><span className="dashboard-online-avatar">{(user.full_name || user.username || "U").trim().charAt(0).toUpperCase()}</span><span className="dashboard-online-rail-copy"><strong>{user.full_name || user.username}</strong><small>{user.roleLabel} · {user.active_sessions || 0} sesiones</small></span><span className="dashboard-online-rail-status">Activo</span></article>)}</div></div> : <div className="dashboard-online-rail-empty"><Icon name="users" /><span>Sin usuarios conectados ahora</span></div>}</section>
    <section className="dashboard-summary-bar dashboard-glass">{model.metrics.map((item) => <button type="button" key={item.key} onClick={() => model.navigate(item.key === "gps" ? "map" : item.key === "records" || item.key === "alerts" ? "records" : "users")}><span>{item.label}</span><strong>{item.value}</strong></button>)}</section>
    <section className="dashboard-new-grid">
      <article className="dashboard-panel dashboard-portfolio"><header><div><span>Situación financiera</span><h2>Resumen de cartera</h2></div><small>{model.padronTotals.barrios} barrios · {model.padronTotals.records.toLocaleString("es-HN")} cuentas</small></header><div className="dashboard-portfolio-total"><span>Mora total del padrón</span><strong>{formatCurrency(model.debtSummary.total || 0)}</strong></div><div className="dashboard-portfolio-kpis"><div><span>Capital</span><strong>{formatCurrency(model.debtSummary.capital || 0)}</strong></div><div><span>Intereses</span><strong>{formatCurrency(model.debtSummary.intereses || 0)}</strong></div><div><span>Cuentas con mora</span><strong>{Number(model.debtSummary.deudores || 0).toLocaleString("es-HN")}</strong></div><div><span>Casos críticos</span><strong>{Number(model.debtSummary.criticos || 0).toLocaleString("es-HN")}</strong></div></div><p>Casos críticos: cuentas con mora igual o mayor a L 1,000.</p></article>
      <article className="dashboard-panel dashboard-debt-panel"><header><div><span>Datos reales del padrón</span><h2>Barrios con mayor mora</h2></div><select value={debtMetric} onChange={(e) => setDebtMetric(e.target.value)}><option value="total">Mora total</option><option value="accounts">Abonados</option><option value="critical">Casos críticos</option></select></header>{ranking.length ? <div className="dashboard-ranking">{ranking.map((item, index) => <button type="button" aria-pressed={selectedBarrios.includes(item.name)} className={selectedBarrios.includes(item.name) ? "is-selected" : ""} key={item.name} onClick={() => toggleBarrio(item.name)}><b>{index + 1}</b><span><strong>{item.name}</strong><i><em style={{ width: `${item.value / maxDebt * 100}%` }} /></i></span><small>{debtMetric === "total" ? formatCurrency(item.value) : item.value.toLocaleString("es-HN")}</small></button>)}</div> : <p className="dashboard-empty">No hay desglose de mora por barrio disponible.</p>}{selectedBarrios.length ? <div className="dashboard-debt-selection"><header><strong>{selectedBarrios.length} {selectedBarrios.length === 1 ? "barrio seleccionado" : "barrios seleccionados"}</strong><button type="button" onClick={() => setSelectedBarrios([])}>Limpiar</button></header><div><span>Capital <b>{formatCurrency(selectedDebt.capital)}</b></span><span>Intereses <b>{formatCurrency(selectedDebt.intereses)}</b></span><span>Mora total <b>{formatCurrency(selectedDebt.total)}</b></span><span>Cuentas <b>{selectedDebt.deudores.toLocaleString("es-HN")}</b></span><span>Críticos <b>{selectedDebt.criticos.toLocaleString("es-HN")}</b></span></div></div> : <p className="dashboard-debt-hint">Selecciona uno o varios barrios para ver el desglose y la sumatoria.</p>}<button className="dashboard-link" onClick={() => model.navigate("mapReports")}>Ver informe</button></article>
      <article className="dashboard-panel dashboard-attention"><header><div><span>Prioridades</span><h2>Atención requerida</h2></div></header>{model.attention.slice(0, 4).map((item) => <button key={item.title} onClick={() => model.navigate(item.actionView)}><Icon name={item.icon} /><span><strong>{item.title}</strong><small>{item.detail}</small></span><b>→</b></button>)}</article>
      <article className="dashboard-panel dashboard-recent"><header><div><span>Aplicación viva</span><h2>Actividad reciente</h2></div></header>{model.feed.slice(0, 5).map((item, index) => <button key={item.key} onClick={() => model.navigate(item.targetView)}><Icon name={item.icon} /><span><strong>{item.title}{index === 0 ? <em>Nuevo</em> : null}</strong><small>{item.detail}</small></span></button>)}</article>
    </section>
  </main>;
}
