import { Router } from "express";
import { banco, bancoAssign, bancoDiscard, bancoListado, bancoTecnicos, bancoUnassign, bancoImport, bancoRestore, bancoSend, bancoVerify, compareFichas, config, createReport, evidence, fichaInternalNotes, fichaState, fichas, history, linkReport, reports, reportState } from "../controllers/clandestinosController.js";
import { imageUpload } from "../middleware/upload.js";

const router = Router();
router.get("/config", config);
router.get("/fichas", fichas);
router.post("/fichas/compare-padrones", compareFichas);
router.patch("/fichas/:id/state", fichaState);
router.patch("/fichas/:id/internal-notes", fichaInternalNotes);
router.get("/history/:entityType/:id", history);
router.get("/reportes", reports);
router.post("/reportes", createReport);
router.patch("/reportes/:id/state", reportState);
router.post("/reportes/:id/link", linkReport);
router.get("/banco", banco);
router.get("/banco/listado", bancoListado);
router.get("/banco/tecnicos", bancoTecnicos);
router.post("/banco/asignar", bancoAssign);
router.post("/banco/desasignar", bancoUnassign);
router.post("/banco/importar", bancoImport);
router.post("/banco/verificar", bancoVerify);
router.post("/banco/:id/enviar", bancoSend);
router.post("/banco/:id/descartar", bancoDiscard);
router.post("/banco/:id/restaurar", bancoRestore);
router.post("/reportes/:id/evidencias", imageUpload.single("evidence"), evidence);
export default router;
