import { useState } from "react";
import { Icon } from "../../../components/Icon";

const blank = { clave_consultada: "", abonado_consultado: "", inmueble_sin_registro: false, nombre_reportado: "", barrio_colonia: "", direccion: "", hallazgo: "", services: { agua: false, alcantarillado: false, tren_aseo: false }, latitude: "", longitude: "", accuracy_meters: "", observaciones_internas: "" };

export default function ReporteTecnicoForm({ api, onCreated, notify }) {
  const [form, setForm] = useState(blank); const [confirmed, setConfirmed] = useState(null); const [photo, setPhoto] = useState(null); const [saving, setSaving] = useState(false);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const confirm = async () => { if (!form.clave_consultada.trim() && !form.abonado_consultado.trim()) { notify("Ingresa una clave o abonado para buscar."); return; } try { const result = await api.fichas({ q: form.clave_consultada || form.abonado_consultado, limit: 5 }); setConfirmed(result.items[0] || false); if (!result.items.length) notify("No hay coincidencia. Puedes marcar inmueble sin registro."); } catch (error) { notify(error.message); } };
  const locate = () => navigator.geolocation?.getCurrentPosition((position) => setForm((current) => ({ ...current, latitude: position.coords.latitude.toFixed(7), longitude: position.coords.longitude.toFixed(7), accuracy_meters: Math.round(position.coords.accuracy) })), () => notify("No fue posible obtener el GPS."), { enableHighAccuracy: true, timeout: 12000 });
  const submit = async (event) => { event.preventDefault(); if (!confirmed && !form.inmueble_sin_registro) { notify("Confirma la referencia o marca inmueble sin registro."); return; } setSaving(true); try { const report = await api.createReport(form); if (photo) await api.evidence(report.id, photo, "Evidencia de campo"); notify(`${report.codigo} enviado a revisión. El padrón no fue modificado.`); setForm(blank); setConfirmed(null); setPhoto(null); onCreated(); } catch (error) { notify(error.message); } finally { setSaving(false); } };
  return <form className="cl-report-form" onSubmit={submit}><div className="cl-flow"><span className="is-active">1<small>Buscar</small></span><span className={confirmed !== null || form.inmueble_sin_registro ? "is-active" : ""}>2<small>Confirmar</small></span><span className={form.hallazgo ? "is-active" : ""}>3<small>Hallazgo</small></span><span className={form.latitude || photo ? "is-active" : ""}>4<small>GPS y fotos</small></span></div>
    <section><h3>1. Buscar y confirmar inmueble</h3><div className="cl-fields"><label><span>Clave catastral</span><input value={form.clave_consultada} onChange={(event) => update("clave_consultada", event.target.value)} /></label><label><span>Abonado</span><input value={form.abonado_consultado} onChange={(event) => update("abonado_consultado", event.target.value)} /></label><button type="button" className="cl-secondary" onClick={confirm}><Icon name="search" />Confirmar referencia</button><label className="cl-check is-wide"><input type="checkbox" checked={form.inmueble_sin_registro} onChange={(event) => { update("inmueble_sin_registro", event.target.checked); if (event.target.checked) setConfirmed(false); }} /><span>Inmueble sin registro</span></label>{confirmed ? <p className="cl-match is-wide"><Icon name="success" /><strong>{confirmed.clave_catastral}</strong> · {confirmed.barrio_colonia || "Sin barrio"}</p> : confirmed === false ? <p className="cl-match is-warning is-wide"><Icon name="warning" />Se reportará sin alterar el padrón.</p> : null}</div></section>
    <section><h3>2. Hallazgo técnico</h3><div className="cl-fields"><label><span>Nombre reportado</span><input value={form.nombre_reportado} onChange={(event) => update("nombre_reportado", event.target.value)} /></label><label><span>Barrio / colonia</span><input value={form.barrio_colonia} onChange={(event) => update("barrio_colonia", event.target.value)} /></label><label className="is-wide"><span>Dirección</span><input value={form.direccion} onChange={(event) => update("direccion", event.target.value)} /></label><label className="is-wide"><span>Descripción del hallazgo</span><textarea required rows="4" value={form.hallazgo} onChange={(event) => update("hallazgo", event.target.value)} /></label><div className="cl-report-services is-wide">{Object.entries({ agua: "Agua", alcantarillado: "Alcantarillado", tren_aseo: "Tren de aseo" }).map(([key,label]) => <label key={key}><input type="checkbox" checked={form.services[key]} onChange={(event) => update("services", { ...form.services, [key]: event.target.checked })} /><span>{label}</span></label>)}</div><label className="is-wide"><span>Observaciones internas</span><textarea rows="3" value={form.observaciones_internas} onChange={(event) => update("observaciones_internas", event.target.value)} /></label></div></section>
    <section><h3>3. GPS y evidencia</h3><div className="cl-fields"><label><span>Latitud</span><input inputMode="decimal" value={form.latitude} onChange={(event) => update("latitude", event.target.value)} /></label><label><span>Longitud</span><input inputMode="decimal" value={form.longitude} onChange={(event) => update("longitude", event.target.value)} /></label><button type="button" className="cl-secondary" onClick={locate}><Icon name="map" />Obtener GPS</button><label className="is-wide"><span>Fotografía</span><input type="file" accept="image/*" capture="environment" onChange={(event) => setPhoto(event.target.files?.[0] || null)} /></label></div></section>
    <footer><p><Icon name="success" />El envío crea un reporte en revisión; nunca cambia el padrón.</p><button type="submit" className="cl-primary" disabled={saving}>{saving ? "Enviando…" : "Enviar a revisión"}<Icon name="arrowRight" /></button></footer>
  </form>;
}
